name: ci-dotnet-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version:
            6.0.x
      - name: Test dotnet
        run: dotnet test
      - name: Execute dotnet
        run: dotnet build BossaBox 